apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: po28b5ack-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: po28b5ack-go 
  name: po28b5ack-go
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: po28b5ack-go
    weight: 100 
